Repository IkramKhan-DevOps/dramabox-neonapps, pull requests merged in 2024-10, with the labels that each got.

#1 New APIs Implemented and Updated previous apis
  src/api/auth/serializer.py
  src/api/auth/views.py
  src/api/v1/pagination.py
  src/api/v1/serializers.py
  src/api/v1/urls.py
  src/services/drama/models.py
  src/services/drama/views.py
  src/web/website/templates/website/include/footer.html
Labels: bug, documentation, duplicate, enhancement

#2 website and backend dynamic portions with new theme added.
  src/api/v1/serializers.py
  src/api/v1/urls.py
  src/api/v1/views.py
  src/services/drama/admin.py
  src/services/drama/models.py
  src/services/drama/views.py
  src/web/admins/templates/admins/include/admin_header.html
  src/web/admins/templates/admins/include/admin_nav.html
  src/web/website/templates/website/base.html
  src/web/website/templates/website/include/footer.html
  src/web/website/templates/website/include/header.html
  src/web/website/templates/website/index.html
  src/web/website/templates/website/privacy_policy.html
  src/web/website/templates/website/terms_and_condition.html
  src/web/website/views.py
  static/website/img/hero/dirilis.jpg
  static/website/img/hero/ertugral.jpg
  static/website/img/hero/ertugral.png
  static/website/img/hero/osman.png
  static/website/img/hero/osman.webp
  static/website/img/logo/white-logo.png
Labels: enhancement

#3 Configure app >> example env added and notification hq removed jazzmi…
  .example.env
  requirements.txt
  root/settings.py
  root/urls.py
Labels: documentation, enhancement

#4 FEAT: Admin Section
  src/services/drama/admin.py
  src/services/drama/models.py
  src/web/admins/forms.py
  src/web/admins/templates/admins/actor_create.html
  src/web/admins/templates/admins/actor_form.html
  src/web/admins/templates/admins/actor_list.html
  src/web/admins/templates/admins/category_create.html
  src/web/admins/templates/admins/category_form.html
  src/web/admins/templates/admins/category_list.html
  src/web/admins/templates/admins/contentrating_create.html
  src/web/admins/templates/admins/contentrating_form.html
  src/web/admins/templates/admins/contentrating_list.html
  src/web/admins/templates/admins/director_create.html
  src/web/admins/templates/admins/director_form.html
  src/web/admins/templates/admins/director_list.html
  src/web/admins/templates/admins/dramaseries_detail.html
  src/web/admins/templates/admins/dramaseries_form.html
  src/web/admins/templates/admins/dramaseries_list.html
  src/web/admins/templates/admins/include/admin_header.html
  src/web/admins/templates/admins/language_create.html
  src/web/admins/templates/admins/language_form.html
  src/web/admins/templates/admins/language_list.html
  src/web/admins/templates/admins/link_categories_dramaseries.html
  src/web/admins/templates/admins/link_languages_dramaseries.html
  src/web/admins/templates/admins/link_tags_dramaseries.html
  src/web/admins/templates/admins/season_create.html
  src/web/admins/templates/admins/season_episode_list.html
  src/web/admins/templates/admins/season_update.html
  src/web/admins/templates/admins/tag_create.html
  src/web/admins/templates/admins/tag_form.html
  src/web/admins/templates/admins/tag_list.html
  src/web/admins/urls.py
  src/web/admins/views.py
Labels: documentation, enhancement

#6 Design Bugs & Forms widget
  src/web/admins/templates/admins/dramaseries_detail.html
  src/web/admins/templates/admins/dramaseries_form.html
  src/web/admins/templates/admins/dramaseries_list.html
  src/web/admins/templates/admins/season_update.html
  src/web/admins/views.py
  static/noimage.jpg
Labels: bug, documentation

#7 Design: Update on drama list
  src/web/admins/templates/admins/dramaseries_list.html
Labels: bug, enhancement
